### ISSUE TITLE
Stuck with sync on shard 2 and 3

### ISSUE THREAD

**Issue by shierzad3007** [seeleteam/go-seele#1018]
The synchronization crashing in shard 2 and 3 , I'm stuck with some errors ( snapshots below )
I've tried to remove .seele and start from the scratch but it is still crashing at some points and doesn't sync farther
How to fix this issue ? Is there any link to download the blockchain database manually
 and paste it to .seele ?
Do I need to open any port for the synchronization ?
Kindly your advice here 
![Block 190891](https://user-images.githubusercontent.com/36801176/67158618-38094200-f343-11e9-946b-7b1715834bad.jpg)
![Error 2](https://user-images.githubusercontent.com/36801176/67158619-38a1d880-f343-11e9-9375-fb9e30cb102d.jpg)
![from the scratch](https://user-images.githubusercontent.com/36801176/67158620-38a1d880-f343-11e9-9c59-ed1920fcf8f1.jpg)

**Comment by shawnxin89** [comment]
Thank you for reporting this issue. We will look into it. It is not caused by the wrong setup of ports. Removing .seele folder usually helps in this case. Did you see the same error after you restarted from the scratch? Currently, we don't provide a download of the blockchain database.

**Comment by shierzad3007** [comment]
I've did remove .seele and started from the scratch several times , still facing the same issue but in different points (sometimes at the beginning in the first blocks and sometimes in the middle of sync )

note : I'm using my home fiber connection , I did try to sync on a dedicated server located in Europe
the sync went smoothly , The latency from my home connection is kind of high in range 180-270 ms depends on the location of the static nodes which I'm pinging to it ( US-China-UK)
the latency from the server is low around 14 ms to UK static nodes as the server located in Europe 
I think the latency is the factor for this issue , in the mining latency playing key factor to get the blocks firstly , Would like to know your opinion , Could be the problem from latency ? is it that sensitive to latency ?

I've solved the issue by getting the blockchain database from one member of the community

**Comment by shawnxin89** [comment]
I don't think this issue is caused by latency. But glad to hear that you get help from the community.

> I've did remove .seele and started from the scratch several times , still facing the same issue but in different points (sometimes at the beginning in the first blocks and sometimes in the middle of sync )
> 
> note : I'm using my home fiber connection , I did try to sync on a dedicated server located in Europe
> the sync went smoothly , The latency from my home connection is kind of high in range 180-270 ms depends on the location of the static nodes which I'm pinging to it ( US-China-UK)
> the latency from the server is low around 14 ms to UK static nodes as the server located in Europe
> I think the latency is the factor for this issue , in the mining latency playing key factor to get the blocks firstly , Would like to know your opinion , Could be the problem from latency ? is it that sensitive to latency ?
> 
> I've solved the issue by getting the blockchain database from one member of the community
