### ISSUE TITLE
Nodes on Shard 1 crashing

### ISSUE THREAD

**Issue by Vibrio787** [seeleteam/go-seele#1021]
Sometime in the region of blocks 1171300-1171700 all three of my Shard 1 nodes crashed.  

End of log as follows:

INFO[100328] got download start event, stop miner          caller="miner.go:191" module=miner
INFO[100328] Miner is stopped.                             caller="miner.go:178" module=miner
INFO[100328] nonce finding aborted                         caller="engine.go:369" module=spow_engine
INFO[100328] nonce finding aborted                         caller="engine.go:369" module=spow_engine
INFO[100328] nonce finding aborted                         caller="engine.go:369" module=spow_engine
INFO[100328] nonce finding aborted                         caller="engine.go:369" module=spow_engine
INFO[100328] nonce finding aborted                         caller="engine.go:369" module=spow_engine
INFO[100328] nonce finding aborted                         caller="engine.go:369" module=spow_engine
INFO[100328] nonce finding aborted                         caller="engine.go:369" module=spow_engine
INFO[100328] nonce finding aborted                         caller="engine.go:369" module=spow_engine
INFO[100328] download end with failed, err=Err occurs when syncing  caller="downloader.go:207" module=download
INFO[100328] got download end event, start miner           caller="miner.go:201" module=miner
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7b1d47]

goroutine 2946637 [running]:
math/big.(*Int).Set(...)
	/usr/lib/go-1.10/src/math/big/int.go:68
github.com/seeleteam/go-seele/core/vm.opGasprice(0xc4242f57f0, 0xc43c318a80, 0xc43259e3c0, 0xc423ed5100, 0xc423ed5120, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc43c316000)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:552 +0x87
github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc43c318a80, 0xc43259e3c0, 0xc42b72e000, 0x184, 0x184, 0xde01550d25dba100, 0x0, 0x0, 0x0, 0x0, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x5a1
github.com/seeleteam/go-seele/core/vm.run(0xc43c316000, 0xc43259e3c0, 0xc42b72e000, 0x184, 0x184, 0x3c00, 0x0, 0x0, 0x0, 0x0, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x1f5
github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc43c316000, 0xcaa3e0, 0xc43259e240, 0x25dba141afd9ca50, 0x626c6b3cde01550d, 0x22009fe5, 0xc42b72e000, 0x184, 0x184, 0x6b35a, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x501
github.com/seeleteam/go-seele/core/vm.opCall(0xc4242f55b8, 0xc43c318a80, 0xc43259e240, 0xc426ae9a40, 0xc426ae9a80, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc43c316000)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:762 +0x2b5
github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc43c318a80, 0xc43259e240, 0xc42a22dc20, 0xe4, 0xe4, 0x91ee303f48356f00, 0x0, 0x0, 0x0, 0x0, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x5a1
github.com/seeleteam/go-seele/core/vm.run(0xc43c316000, 0xc43259e240, 0xc42a22dc20, 0xe4, 0xe4, 0x5f00, 0x0, 0x0, 0x0, 0x0, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x1f5
github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc43c316000, 0xcaa3e0, 0xc43259e180, 0x48356f902824f89e, 0x8858298d91ee303f, 0x2200f414, 0xc42a22dc20, 0xe4, 0xe4, 0x704eb, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x501
github.com/seeleteam/go-seele/core/vm.opCall(0xc4242f52f8, 0xc43c318a80, 0xc43259e180, 0xc422d69f40, 0xc426ae8680, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc43c316000)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:762 +0x2b5
github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc43c318a80, 0xc43259e180, 0xc430cf3b30, 0x24, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x5a1
github.com/seeleteam/go-seele/core/vm.run(0xc43c316000, 0xc43259e180, 0xc430cf3b30, 0x24, 0x24, 0x3000, 0x0, 0x0, 0x0, 0x0, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x1f5
github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc43c316000, 0xcab420, 0xc433d60e80, 0x34fdae56f7d72720, 0x38254bf96712ef11, 0xc43200e386, 0xc430cf3b30, 0x24, 0x24, 0x74d48, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x501
github.com/seeleteam/go-seele/core/svm.processEvmContract(0xc423eb1dd0, 0x74d48, 0xc43c31da34, 0x123fc80, 0x0)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/svm/svm.go:193 +0x49a
github.com/seeleteam/go-seele/core/svm.Process(0xc423eb1dd0, 0x11e0ce, 0xcacbe0, 0xc425288120, 0x11e0ce)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/svm/svm.go:56 +0x610
github.com/seeleteam/go-seele/core.(*Blockchain).ApplyTransaction(0xc4200d8d20, 0xc422904000, 0x1, 0x551fc5f507e09bc0, 0xdb579b0deb6b4bb5, 0x911bc58a, 0xc425288120, 0xc424be1900, 0x0, 0xc4244bec00, ...)
	/home/seele/go/src/github.com/seeleteam/go-seele/core/blockchain.go:573 +0xbb
github.com/seeleteam/go-seele/miner.(*Task).chooseTransactions(0xc4240a6200, 0xcaf2a0, 0xc4206d6780, 0xc425288120, 0xc4200cc048, 0x100000)
	/home/seele/go/src/github.com/seeleteam/go-seele/miner/task.go:149 +0x357
github.com/seeleteam/go-seele/miner.(*Task).applyTransactionsAndDebts(0xc4240a6200, 0xcaf2a0, 0xc4206d6780, 0xc425288120, 0xc4200cc048, 0x0, 0xc4201e4e00)
	/home/seele/go/src/github.com/seeleteam/go-seele/miner/task.go:57 +0x16a
github.com/seeleteam/go-seele/miner.(*Miner).prepareNewBlock(0xc420684000, 0xc4206e6ae0, 0xc4200cec80, 0x0)
	/home/seele/go/src/github.com/seeleteam/go-seele/miner/miner.go:293 +0x5ca
github.com/seeleteam/go-seele/miner.(*Miner).Start(0xc420684000, 0xc15075, 0x23)
	/home/seele/go/src/github.com/seeleteam/go-seele/miner/miner.go:137 +0x13c
github.com/seeleteam/go-seele/miner.(*Miner).downloaderEventCallback(0xc420684000, 0xafa580, 0xc9dbc0)
	/home/seele/go/src/github.com/seeleteam/go-seele/miner/miner.go:202 +0xb7
github.com/seeleteam/go-seele/miner.(*Miner).(github.com/seeleteam/go-seele/miner.downloaderEventCallback)-fm(0xafa580, 0xc9dbc0)
	/home/seele/go/src/github.com/seeleteam/go-seele/miner/miner.go:83 +0x3e
created by github.com/seeleteam/go-seele/event.(*EventManager).Fire
	/home/seele/go/src/github.com/seeleteam/go-seele/event/manager.go:27 +0xcd

**Comment by shawnxin89** [comment]
> Sometime in the region of blocks 1171300-1171700 all three of my Shard 1 nodes crashed.
> 
> End of log as follows:
> 
> INFO[100328] got download start event, stop miner caller="miner.go:191" module=miner
> INFO[100328] Miner is stopped. caller="miner.go:178" module=miner
> INFO[100328] nonce finding aborted caller="engine.go:369" module=spow_engine
> INFO[100328] nonce finding aborted caller="engine.go:369" module=spow_engine
> INFO[100328] nonce finding aborted caller="engine.go:369" module=spow_engine
> INFO[100328] nonce finding aborted caller="engine.go:369" module=spow_engine
> INFO[100328] nonce finding aborted caller="engine.go:369" module=spow_engine
> INFO[100328] nonce finding aborted caller="engine.go:369" module=spow_engine
> INFO[100328] nonce finding aborted caller="engine.go:369" module=spow_engine
> INFO[100328] nonce finding aborted caller="engine.go:369" module=spow_engine
> INFO[100328] download end with failed, err=Err occurs when syncing caller="downloader.go:207" module=download
> INFO[100328] got download end event, start miner caller="miner.go:201" module=miner
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7b1d47]
> 
> goroutine 2946637 [running]:
> math/big.(*Int).Set(...)
> /usr/lib/go-1.10/src/math/big/int.go:68
> github.com/seeleteam/go-seele/core/vm.opGasprice(0xc4242f57f0, 0xc43c318a80, 0xc43259e3c0, 0xc423ed5100, 0xc423ed5120, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc43c316000)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:552 +0x87
> github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc43c318a80, 0xc43259e3c0, 0xc42b72e000, 0x184, 0x184, 0xde01550d25dba100, 0x0, 0x0, 0x0, 0x0, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x5a1
> github.com/seeleteam/go-seele/core/vm.run(0xc43c316000, 0xc43259e3c0, 0xc42b72e000, 0x184, 0x184, 0x3c00, 0x0, 0x0, 0x0, 0x0, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x1f5
> github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc43c316000, 0xcaa3e0, 0xc43259e240, 0x25dba141afd9ca50, 0x626c6b3cde01550d, 0x22009fe5, 0xc42b72e000, 0x184, 0x184, 0x6b35a, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x501
> github.com/seeleteam/go-seele/core/vm.opCall(0xc4242f55b8, 0xc43c318a80, 0xc43259e240, 0xc426ae9a40, 0xc426ae9a80, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc43c316000)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:762 +0x2b5
> github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc43c318a80, 0xc43259e240, 0xc42a22dc20, 0xe4, 0xe4, 0x91ee303f48356f00, 0x0, 0x0, 0x0, 0x0, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x5a1
> github.com/seeleteam/go-seele/core/vm.run(0xc43c316000, 0xc43259e240, 0xc42a22dc20, 0xe4, 0xe4, 0x5f00, 0x0, 0x0, 0x0, 0x0, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x1f5
> github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc43c316000, 0xcaa3e0, 0xc43259e180, 0x48356f902824f89e, 0x8858298d91ee303f, 0x2200f414, 0xc42a22dc20, 0xe4, 0xe4, 0x704eb, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x501
> github.com/seeleteam/go-seele/core/vm.opCall(0xc4242f52f8, 0xc43c318a80, 0xc43259e180, 0xc422d69f40, 0xc426ae8680, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc43c316000)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:762 +0x2b5
> github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc43c318a80, 0xc43259e180, 0xc430cf3b30, 0x24, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x5a1
> github.com/seeleteam/go-seele/core/vm.run(0xc43c316000, 0xc43259e180, 0xc430cf3b30, 0x24, 0x24, 0x3000, 0x0, 0x0, 0x0, 0x0, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x1f5
> github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc43c316000, 0xcab420, 0xc433d60e80, 0x34fdae56f7d72720, 0x38254bf96712ef11, 0xc43200e386, 0xc430cf3b30, 0x24, 0x24, 0x74d48, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x501
> github.com/seeleteam/go-seele/core/svm.processEvmContract(0xc423eb1dd0, 0x74d48, 0xc43c31da34, 0x123fc80, 0x0)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/svm/svm.go:193 +0x49a
> github.com/seeleteam/go-seele/core/svm.Process(0xc423eb1dd0, 0x11e0ce, 0xcacbe0, 0xc425288120, 0x11e0ce)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/svm/svm.go:56 +0x610
> github.com/seeleteam/go-seele/core.(*Blockchain).ApplyTransaction(0xc4200d8d20, 0xc422904000, 0x1, 0x551fc5f507e09bc0, 0xdb579b0deb6b4bb5, 0x911bc58a, 0xc425288120, 0xc424be1900, 0x0, 0xc4244bec00, ...)
> /home/seele/go/src/github.com/seeleteam/go-seele/core/blockchain.go:573 +0xbb
> github.com/seeleteam/go-seele/miner.(*Task).chooseTransactions(0xc4240a6200, 0xcaf2a0, 0xc4206d6780, 0xc425288120, 0xc4200cc048, 0x100000)
> /home/seele/go/src/github.com/seeleteam/go-seele/miner/task.go:149 +0x357
> github.com/seeleteam/go-seele/miner.(*Task).applyTransactionsAndDebts(0xc4240a6200, 0xcaf2a0, 0xc4206d6780, 0xc425288120, 0xc4200cc048, 0x0, 0xc4201e4e00)
> /home/seele/go/src/github.com/seeleteam/go-seele/miner/task.go:57 +0x16a
> github.com/seeleteam/go-seele/miner.(*Miner).prepareNewBlock(0xc420684000, 0xc4206e6ae0, 0xc4200cec80, 0x0)
> /home/seele/go/src/github.com/seeleteam/go-seele/miner/miner.go:293 +0x5ca
> github.com/seeleteam/go-seele/miner.(*Miner).Start(0xc420684000, 0xc15075, 0x23)
> /home/seele/go/src/github.com/seeleteam/go-seele/miner/miner.go:137 +0x13c
> github.com/seeleteam/go-seele/miner.(*Miner).downloaderEventCallback(0xc420684000, 0xafa580, 0xc9dbc0)
> /home/seele/go/src/github.com/seeleteam/go-seele/miner/miner.go:202 +0xb7
> github.com/seeleteam/go-seele/miner.(*Miner).(github.com/seeleteam/go-seele/miner.downloaderEventCallback)-fm(0xafa580, 0xc9dbc0)
> /home/seele/go/src/github.com/seeleteam/go-seele/miner/miner.go:83 +0x3e
> created by github.com/seeleteam/go-seele/event.(*EventManager).Fire
> /home/seele/go/src/github.com/seeleteam/go-seele/event/manager.go:27 +0xcd


Thank you for your feedback. We've noticed it and released a version 1.2.2 to fix this issue.
