### ISSUE TITLE
I don't know why these msgs come out endlessly?

### ISSUE THREAD

**Issue by alphyoung** [seeleteam/go-seele#1023]
ERRO[1580] failed to apply tx 0x6aa14f2e3db36a93d913bd99775a0ff3a6bb33a17f7add2515970bf43b47381e, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[1580] failed to apply tx 0x909f9a79ebadd4461f6296e357001a8e757401677739b19386fa97e7f8ddac27, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[1580] failed to apply tx 0x4e1fd52170175580dd70449ba01e95e12b72fea94e608b39003fd7ae5b3553c9, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[1580] failed to apply tx 0x8daae43440939cfa3685bb6a16d1851d273d6600a9b1bd91a1729e0adab5d405, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[1580] failed to apply tx 0x91c455635170aac21c2a6ae85b5ac389a98eb6656363d3f887c6905b64dbf150, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[1580] failed to apply tx 0x5813be0ec6d5a85ec71bf905f0f2a34b85736aafb0afb83c518c3d43051841ec, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner

**Comment by shawnxin89** [comment]
> ERRO[1580] failed to apply tx 0x6aa14f2e3db36a93d913bd99775a0ff3a6bb33a17f7add2515970bf43b47381e, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner
> ERRO[1580] failed to apply tx 0x909f9a79ebadd4461f6296e357001a8e757401677739b19386fa97e7f8ddac27, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner
> ERRO[1580] failed to apply tx 0x4e1fd52170175580dd70449ba01e95e12b72fea94e608b39003fd7ae5b3553c9, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner
> ERRO[1580] failed to apply tx 0x8daae43440939cfa3685bb6a16d1851d273d6600a9b1bd91a1729e0adab5d405, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner
> ERRO[1580] failed to apply tx 0x91c455635170aac21c2a6ae85b5ac389a98eb6656363d3f887c6905b64dbf150, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner
> ERRO[1580] failed to apply tx 0x5813be0ec6d5a85ec71bf905f0f2a34b85736aafb0afb83c518c3d43051841ec, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner

It seems to be a tx related to smart contracts. It's normal for an invalid tx to be rejected.

**Comment by alphyoung** [comment]
I cannot understand why these lines appears periodically

**Comment by alphyoung** [comment]
These lines recur every 1 second at a purely new computer.

`INFO[0182] write back local blocks: 4800                 caller="downloader.go:599" module=download
INFO[0182] write back local blocks: 4801                 caller="downloader.go:599" module=download
INFO[0182] write back local blocks: 4802                 caller="downloader.go:599" module=download
INFO[0182] write back local blocks: 4803                 caller="downloader.go:599" module=download
INFO[0182] download end with failed, err=Err occurs when syncing  caller="downloader.go:207" module=download
`

**Comment by shawnxin89** [comment]
> These lines recur every 1 second at a purely new computer.
> 
> `INFO[0182] write back local blocks: 4800 caller="downloader.go:599" module=download INFO[0182] write back local blocks: 4801 caller="downloader.go:599" module=download INFO[0182] write back local blocks: 4802 caller="downloader.go:599" module=download INFO[0182] write back local blocks: 4803 caller="downloader.go:599" module=download INFO[0182] download end with failed, err=Err occurs when syncing caller="downloader.go:207" module=download `

This is due to the failure of writing new block. We will look into it. You can try 
./node start ....     -m stop 
to not start mining when you start synchronizing from scratch. This could help with your synchronization.

**Comment by alphyoung** [comment]
The same lines endlessly come out:
`ERRO[28301] failed to apply tx 0x6aa14f2e3db36a93d913bd99775a0ff3a6bb33a17f7add2515970bf43b47381e, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[28301] failed to apply tx 0x909f9a79ebadd4461f6296e357001a8e757401677739b19386fa97e7f8ddac27, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[28301] failed to apply tx 0x4e1fd52170175580dd70449ba01e95e12b72fea94e608b39003fd7ae5b3553c9, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[28301] failed to apply tx 0x8daae43440939cfa3685bb6a16d1851d273d6600a9b1bd91a1729e0adab5d405, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[28301] failed to apply tx 0x91c455635170aac21c2a6ae85b5ac389a98eb6656363d3f887c6905b64dbf150, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
ERRO[28301] failed to apply tx 0x5813be0ec6d5a85ec71bf905f0f2a34b85736aafb0afb83c518c3d43051841ec, failed to process tx via svm ===> evm: execution reverted  caller="task.go:152" module=miner
`

**Comment by shawnxin89** [comment]
> The same lines endlessly come out:
> `ERRO[28301] failed to apply tx 0x6aa14f2e3db36a93d913bd99775a0ff3a6bb33a17f7add2515970bf43b47381e, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner ERRO[28301] failed to apply tx 0x909f9a79ebadd4461f6296e357001a8e757401677739b19386fa97e7f8ddac27, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner ERRO[28301] failed to apply tx 0x4e1fd52170175580dd70449ba01e95e12b72fea94e608b39003fd7ae5b3553c9, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner ERRO[28301] failed to apply tx 0x8daae43440939cfa3685bb6a16d1851d273d6600a9b1bd91a1729e0adab5d405, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner ERRO[28301] failed to apply tx 0x91c455635170aac21c2a6ae85b5ac389a98eb6656363d3f887c6905b64dbf150, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner ERRO[28301] failed to apply tx 0x5813be0ec6d5a85ec71bf905f0f2a34b85736aafb0afb83c518c3d43051841ec, failed to process tx via svm ===> evm: execution reverted caller="task.go:152" module=miner `

We fix this issue in version >= v1.2.3.
