### ISSUE TITLE
 transactions very slow in shard1

### ISSUE THREAD

**Issue by lkbtboy** [seeleteam/go-seele#1037]
submit 4 txs to 4 shards, tx in shard 2,3,4 was blocked very soon, but tx in shard 1 is very slow, maybe 20-40 minutes or more. More interestingly, txs in shard 1 was blocked by miners those almost don't mine blocks,such as 0xdaa988142afff9cc746b201d8960921f885cdd51 . But the miner(0x6a9c3adf6354cb1e269ac3c392ca16ffcf61e8e1,0x9aca75724534482299173d4b12204afd36b89631） controll the shard1's block they don't include  transactions in the mined block.
Is there a big issue in shard1? why the tx is blocked so slow?

**Comment by D3m1tx** [comment]
Hi,
I'm having the same issue, and yes, i think there is a problem with shard1 as I'm mining 10% of what I mined last week.

**Comment by shawnxin89** [comment]
> submit 4 txs to 4 shards, tx in shard 2,3,4 was blocked very soon, but tx in shard 1 is very slow, maybe 20-40 minutes or more. More interestingly, txs in shard 1 was blocked by miners those almost don't mine blocks,such as 0xdaa988142afff9cc746b201d8960921f885cdd51 . But the miner(0x6a9c3adf6354cb1e269ac3c392ca16ffcf61e8e1,0x9aca75724534482299173d4b12204afd36b89631） controll the shard1's block they don't include transactions in the mined block.
> Is there a big issue in shard1? why the tx is blocked so slow?

We will investigate this issue. For now, if the tx takes too long to be blocked, you can send a new tx with higher tx fee(by wallet or terminal) or increase the tx nonce(only by terminal). The new tx will kind of "overwrite" the old one. If the new one is blocked, the old one will never be blocked.

**Comment by lkbtboy** [comment]
Hi shawn,
Thanks for the reply.
 But it is not a good way for solving the issue. The problem is txs are blocked too hardly. 
 For developing apps on the seele,it is not friendly, such as exchange, smart contract apps. 
 Pls fix it asap on the shard1,we are developing DApps on the seele.
Seele Sharding Technology for high throughput concurrency with 2000 TPS in the Seele main-net currently, not waiting 20-40 minutes  for some txs :)

**Comment by troytrojan01** [comment]
Ikbtboy,
I think your issue is isolated. I just sent a transaction on shard1 and it took ~20 seconds to appear in the destination address. seelescan it took about 4 minutes to appear, but it was on-chain and transacted in seconds. This isn't the first time i've used shard1 either. I've never had the issues that you speak of. This appears to be operator error and not understanding the fee construct.

**Comment by liusl0628** [comment]
Hi shawn & troytrojan01
I'm having the same issue,txs in shard1 were blocked too long time,sometimes.
