### ISSUE TITLE
[Improvement] client sendtx is always executed against shard1 node

### ISSUE THREAD

**Issue by D3m1tx** [seeleteam/go-seele#1038]
Hi,

Can we get a port parameter in client sendtx command? It seems like it is always launched against shard1 node and if we don't have a node1 running is failing.

Thanks,

**Comment by shawnxin89** [comment]
> Hi,
> 
> Can we get a port parameter in client sendtx command? It seems like it is always launched against shard1 node and if we don't have a node1 running is failing.
> 
> Thanks,

You can choose a shard1 node ending with port 8027 from the static nodes in the config file.  Then do       ./client sendtx ....... -a ip：port

**Comment by shawnxin89** [comment]
> Hi,
> 
> Can we get a port parameter in client sendtx command? It seems like it is always launched against shard1 node and if we don't have a node1 running is failing.
> 
> Thanks,

Or you may want to use our wallet to send tx.

**Comment by D3m1tx** [comment]
I didn't see -a parameter. 
Thank you!!
