### ISSUE TITLE
Error synchronizing shard 1

### ISSUE THREAD

**Issue by D3m1tx** [seeleteam/go-seele#1042]
Hi,

I'm having this error synchronizing shard 1 without mining.

```
[36mcaller[0m="server.go:261" [36mmodule[0m=p2p
[36mINFO[0m[0164] got download start event, stop miner          [36mcaller[0m="miner.go:191" [36mmodule[0m=miner
[36mINFO[0m[0165] lightchain, shard: 3, local height: 1327398, best peer: 0x905d20cf46167d83ada3c252378982be27db0d41, peer height: 1327399  [36mcaller[0m="protocol.go:219" [36mmodule[0m=lightclient_3
[36mINFO[0m[0165] lightchain, shard: 4, local height: 1316145, best peer: 0xc8a4b5f0d97bb8f1a528d609e79550579ab6b5b1, peer height: 1316145  [36mcaller[0m="protocol.go:219" [36mmodule[0m=lightclient_4
[36mINFO[0m[0165] lightchain, shard: 2, local height: 1306836, no peer connected  [36mcaller[0m="protocol.go:214" [36mmodule[0m=lightclient_2
[36mINFO[0m[0165]  [240] blocks will be processed into local database  [36mcaller[0m="downloader.go:573" [36mmodule[0m=download
[36mINFO[0m[0165] got block message and save it. height=1256536, hash=0xfd846bc722c29e572bb3d6d7a7854aed567fe722d88f18bf26115bad739a4a5f, time=1573585045047185700  [36mcaller[0m="downloader.go:577" [36mmodule[0m=download
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x81b3c5]

goroutine 735 [running]:
math/big.(*Int).Set(...)
        C:/Go/src/math/big/int.go:75
github.com/seeleteam/go-seele/core/vm.opGasprice(0xc0037431e0, 0xc003106a80, 0xc003a6a300, 0xc0029f4220, 0xc0029f4240, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc003104000)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:552 +0x75
github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc003106a80, 0xc003a6a300, 0xc000310d00, 0x184, 0x184, 0x22009fe5626c6b00, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x59e
github.com/seeleteam/go-seele/core/vm.run(0xc003104000, 0xc003a6a300, 0xc000310d00, 0x184, 0x184, 0x3c00, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x29e
github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc003104000, 0xe06c80, 0xc003a6a180, 0x25dba141afd9ca50, 0x626c6b3cde01550d, 0xc022009fe5, 0xc000310d00, 0x184, 0x184, 0x6b35a, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x520
github.com/seeleteam/go-seele/core/vm.opCall(0xc0037429b8, 0xc003106a80, 0xc003a6a180, 0xc002a2dae0, 0xc002a2db00, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc003104000)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:762 +0x31a
github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc003106a80, 0xc003a6a180, 0xc002974ff0, 0xe4, 0xe4, 0x2200f41488582900, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x59e
github.com/seeleteam/go-seele/core/vm.run(0xc003104000, 0xc003a6a180, 0xc002974ff0, 0xe4, 0xe4, 0x5f00, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x29e
github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc003104000, 0xe06c80, 0xc003a6a0c0, 0x48356f902824f89e, 0x8858298d91ee303f, 0xc02200f414, 0xc002974ff0, 0xe4, 0xe4, 0x704eb, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x520
github.com/seeleteam/go-seele/core/vm.opCall(0xc003742360, 0xc003106a80, 0xc003a6a0c0, 0xc002a2cd20, 0xc002a2cd40, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc003104000)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:762 +0x31a
github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc003106a80, 0xc003a6a0c0, 0xc002d4c300, 0x24, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x59e
github.com/seeleteam/go-seele/core/vm.run(0xc003104000, 0xc003a6a0c0, 0xc002d4c300, 0x24, 0x24, 0x3000, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x29e
github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc003104000, 0xe07bc0, 0xc004ab27e0, 0x34fdae56f7d72720, 0x38254bf96712ef11, 0x3200e386, 0xc002d4c300, 0x24, 0x24, 0x74d48, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x520
github.com/seeleteam/go-seele/core/svm.processEvmContract(0xc0030370b0, 0x74d48, 0xc0023e742c, 0x1318ee0, 0x0)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/svm/svm.go:193 +0x537
github.com/seeleteam/go-seele/core/svm.Process(0xc0030370b0, 0x132c58, 0xc003742068, 0xbc7fa0, 0xc002d7e080)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/svm/svm.go:56 +0x66c
github.com/seeleteam/go-seele/core.(*Blockchain).ApplyTransaction(0xc0001a2aa0, 0xc0048d8420, 0x1, 0x7d26b596222b1854, 0x37a824789f21511e, 0x219ef871, 0xc001857d40, 0xc003f9a3c0, 0x1b, 0x8, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:573 +0xb3
github.com/seeleteam/go-seele/core.(*Blockchain).applyRewardAndRegularTxs(0xc0001a2aa0, 0xc001857d40, 0xc0048d82c0, 0xc0004c8698, 0x9, 0xc, 0xc003f9a3c0, 0x0, 0x0, 0x3, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:551 +0x5dc
github.com/seeleteam/go-seele/core.(*Blockchain).applyTxs(0xc0001a2aa0, 0xc001a905a0, 0xe32af1c53e4ff0f9, 0x7f827e6b71ba89d3, 0x6162bfba77330ab1, 0x71143dce64a4f9fe, 0x0, 0x0, 0x770000006f, 0x6c0000006e, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:511 +0x456
github.com/seeleteam/go-seele/core.(*Blockchain).doWriteBlock(0xc0001a2aa0, 0xc001a905a0, 0x0, 0x0)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:298 +0x5da
github.com/seeleteam/go-seele/core.(*Blockchain).WriteBlock(0xc0001a2aa0, 0xc001a905a0, 0x3a, 0xc0023e7ed8)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:262 +0x62
github.com/seeleteam/go-seele/seele/download.(*Downloader).processBlocks(0xc003139480, 0xc0057b0000, 0xf0, 0x9418, 0x132c57, 0x132c57, 0xc002d04780, 0x1318178, 0x0, 0x0, ...)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/seele/download/downloader.go:579 +0x29d
github.com/seeleteam/go-seele/seele/download.(*taskMgr).run(0xc001bac1c0)
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/seele/download/taskMgr.go:101 +0xd7
created by github.com/seeleteam/go-seele/seele/download.newTaskMgr
        C:/Users/micha/go/src/github.com/seeleteam/go-seele/seele/download/taskMgr.go:91 +0x247
```

**Comment by horusseelle** [comment]
> Hi,
> 
> I'm having this error synchronizing shard 1 without mining.
> 
> ```
> �[36mcaller�[0m="server.go:261" �[36mmodule�[0m=p2p
> �[36mINFO�[0m[0164] got download start event, stop miner          �[36mcaller�[0m="miner.go:191" �[36mmodule�[0m=miner
> �[36mINFO�[0m[0165] lightchain, shard: 3, local height: 1327398, best peer: 0x905d20cf46167d83ada3c252378982be27db0d41, peer height: 1327399  �[36mcaller�[0m="protocol.go:219" �[36mmodule�[0m=lightclient_3
> �[36mINFO�[0m[0165] lightchain, shard: 4, local height: 1316145, best peer: 0xc8a4b5f0d97bb8f1a528d609e79550579ab6b5b1, peer height: 1316145  �[36mcaller�[0m="protocol.go:219" �[36mmodule�[0m=lightclient_4
> �[36mINFO�[0m[0165] lightchain, shard: 2, local height: 1306836, no peer connected  �[36mcaller�[0m="protocol.go:214" �[36mmodule�[0m=lightclient_2
> �[36mINFO�[0m[0165]  [240] blocks will be processed into local database  �[36mcaller�[0m="downloader.go:573" �[36mmodule�[0m=download
> �[36mINFO�[0m[0165] got block message and save it. height=1256536, hash=0xfd846bc722c29e572bb3d6d7a7854aed567fe722d88f18bf26115bad739a4a5f, time=1573585045047185700  �[36mcaller�[0m="downloader.go:577" �[36mmodule�[0m=download
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x10 pc=0x81b3c5]
> 
> goroutine 735 [running]:
> math/big.(*Int).Set(...)
>         C:/Go/src/math/big/int.go:75
> github.com/seeleteam/go-seele/core/vm.opGasprice(0xc0037431e0, 0xc003106a80, 0xc003a6a300, 0xc0029f4220, 0xc0029f4240, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc003104000)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:552 +0x75
> github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc003106a80, 0xc003a6a300, 0xc000310d00, 0x184, 0x184, 0x22009fe5626c6b00, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x59e
> github.com/seeleteam/go-seele/core/vm.run(0xc003104000, 0xc003a6a300, 0xc000310d00, 0x184, 0x184, 0x3c00, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x29e
> github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc003104000, 0xe06c80, 0xc003a6a180, 0x25dba141afd9ca50, 0x626c6b3cde01550d, 0xc022009fe5, 0xc000310d00, 0x184, 0x184, 0x6b35a, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x520
> github.com/seeleteam/go-seele/core/vm.opCall(0xc0037429b8, 0xc003106a80, 0xc003a6a180, 0xc002a2dae0, 0xc002a2db00, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc003104000)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:762 +0x31a
> github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc003106a80, 0xc003a6a180, 0xc002974ff0, 0xe4, 0xe4, 0x2200f41488582900, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x59e
> github.com/seeleteam/go-seele/core/vm.run(0xc003104000, 0xc003a6a180, 0xc002974ff0, 0xe4, 0xe4, 0x5f00, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x29e
> github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc003104000, 0xe06c80, 0xc003a6a0c0, 0x48356f902824f89e, 0x8858298d91ee303f, 0xc02200f414, 0xc002974ff0, 0xe4, 0xe4, 0x704eb, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x520
> github.com/seeleteam/go-seele/core/vm.opCall(0xc003742360, 0xc003106a80, 0xc003a6a0c0, 0xc002a2cd20, 0xc002a2cd40, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc003104000)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/instructions.go:762 +0x31a
> github.com/seeleteam/go-seele/core/vm.(*EVMInterpreter).Run(0xc003106a80, 0xc003a6a0c0, 0xc002d4c300, 0x24, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/interpreter.go:257 +0x59e
> github.com/seeleteam/go-seele/core/vm.run(0xc003104000, 0xc003a6a0c0, 0xc002d4c300, 0x24, 0x24, 0x3000, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:64 +0x29e
> github.com/seeleteam/go-seele/core/vm.(*EVM).Call(0xc003104000, 0xe07bc0, 0xc004ab27e0, 0x34fdae56f7d72720, 0x38254bf96712ef11, 0x3200e386, 0xc002d4c300, 0x24, 0x24, 0x74d48, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/vm/evm.go:231 +0x520
> github.com/seeleteam/go-seele/core/svm.processEvmContract(0xc0030370b0, 0x74d48, 0xc0023e742c, 0x1318ee0, 0x0)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/svm/svm.go:193 +0x537
> github.com/seeleteam/go-seele/core/svm.Process(0xc0030370b0, 0x132c58, 0xc003742068, 0xbc7fa0, 0xc002d7e080)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/svm/svm.go:56 +0x66c
> github.com/seeleteam/go-seele/core.(*Blockchain).ApplyTransaction(0xc0001a2aa0, 0xc0048d8420, 0x1, 0x7d26b596222b1854, 0x37a824789f21511e, 0x219ef871, 0xc001857d40, 0xc003f9a3c0, 0x1b, 0x8, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:573 +0xb3
> github.com/seeleteam/go-seele/core.(*Blockchain).applyRewardAndRegularTxs(0xc0001a2aa0, 0xc001857d40, 0xc0048d82c0, 0xc0004c8698, 0x9, 0xc, 0xc003f9a3c0, 0x0, 0x0, 0x3, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:551 +0x5dc
> github.com/seeleteam/go-seele/core.(*Blockchain).applyTxs(0xc0001a2aa0, 0xc001a905a0, 0xe32af1c53e4ff0f9, 0x7f827e6b71ba89d3, 0x6162bfba77330ab1, 0x71143dce64a4f9fe, 0x0, 0x0, 0x770000006f, 0x6c0000006e, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:511 +0x456
> github.com/seeleteam/go-seele/core.(*Blockchain).doWriteBlock(0xc0001a2aa0, 0xc001a905a0, 0x0, 0x0)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:298 +0x5da
> github.com/seeleteam/go-seele/core.(*Blockchain).WriteBlock(0xc0001a2aa0, 0xc001a905a0, 0x3a, 0xc0023e7ed8)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/core/blockchain.go:262 +0x62
> github.com/seeleteam/go-seele/seele/download.(*Downloader).processBlocks(0xc003139480, 0xc0057b0000, 0xf0, 0x9418, 0x132c57, 0x132c57, 0xc002d04780, 0x1318178, 0x0, 0x0, ...)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/seele/download/downloader.go:579 +0x29d
> github.com/seeleteam/go-seele/seele/download.(*taskMgr).run(0xc001bac1c0)
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/seele/download/taskMgr.go:101 +0xd7
> created by github.com/seeleteam/go-seele/seele/download.newTaskMgr
>         C:/Users/micha/go/src/github.com/seeleteam/go-seele/seele/download/taskMgr.go:91 +0x247
> ```

What is your current version? Please make sure it is the latest version. We've fixed this issue a few weeks ago.

**Comment by D3m1tx** [comment]
You are right, this is the only node that i forgot to update, my mistake.

Thank you!!
