### ISSUE TITLE
Can anyone Explane what is this WARN?

### ISSUE THREAD

**Issue by frode88** [seeleteam/go-seele#1059]
![Skjermbilde](https://user-images.githubusercontent.com/22121200/69496427-6645e880-0ed2-11ea-9f20-83308035f0d0.PNG)

**Comment by frode88** [comment]
HI.
one more thing. why miner hashrate dosent work?

root@vultr:~/go/src/github.com/seeleteam/go-seele/build# ./client miner hashrate -a  127.0.0.1:8027
2019/11/24 16:00:00 Failed to call rpc, The method miner_getHashrate does not exist/is not available

**Comment by troytrojan01** [comment]
I raised the issue about the hashrate command a while back. No action taken on it.

https://github.com/seeleteam/go-seele/issues/1015#issue-500527714

**Comment by frode88** [comment]
> I raised the issue about the hashrate command a while back. No action taken on it.
> 
> [#1015 (comment)](https://github.com/seeleteam/go-seele/issues/1015#issue-500527714)

yeah will make life esay if we see hash rate. now mining 8 core 2 days no block.. about to give up:S

**Comment by frode88** [comment]
![Skjermbilde](https://user-images.githubusercontent.com/22121200/69497766-d22f4d80-0ee0-11ea-9c67-e18d7c22ee01.PNG)
 and this issue. I did change ulimit thing and still get this erro

**Comment by frode88** [comment]
@troytrojan01 Hi. do you have nativ Seele? my adress dosent show in explorer. Can you send me 0.1 Seele to see if my adress show in explorer? thank you.

**Comment by troytrojan01** [comment]
Yes. Post address

**Comment by frode88** [comment]
> Yes. Post address

Thank you.

here is my adress Shard 1

0xa31055a0f98548d4bca9c4ed45573b6d94876c11

**Comment by troytrojan01** [comment]
ok. doing it now

**Comment by frode88** [comment]
> ok. doing it now

Thank you alot:)

**Comment by frode88** [comment]
> ok. doing it now

got it- still dosent show on explorer:S

**Comment by troytrojan01** [comment]
![seele](https://user-images.githubusercontent.com/39805603/69501088-0eee4b00-0ec7-11ea-9edb-e5fa7734aa87.PNG)

**Comment by frode88** [comment]
Finaly! thank you alot! now i search and find my adress. so every adress have to have balance to show on explorer:)

**Comment by troytrojan01** [comment]
> Finaly! thank you alot! now i search and find my adress. so every adress have to have balance to show on explorer:)

That's correct. I dealt with the same issue early on.

**Comment by frode88** [comment]
> > Finaly! thank you alot! now i search and find my adress. so every adress have to have balance to show on explorer:)
> 
> That's correct. I dealt with the same issue early on.

Can I ask you what you use(vps, wich cpu) to mine? im running 8 core 24hours and no reward..:S

**Comment by troytrojan01** [comment]
> > > Finaly! thank you alot! now i search and find my adress. so every adress have to have balance to show on explorer:)
> > 
> > 
> > That's correct. I dealt with the same issue early on.
> 
> Can I ask you what you use(vps, wich cpu) to mine? im running 8 core 24hours and no reward..:S

I was using multiple VPS (24 core) and a bare metal server (8 core) early in the process. once mining started having issues, I switched to my desktop. It started out OK. The past couple of weeks have been awful though. I literally got 1 block after several days today. Not sure if it's the shard or what. I primarily mine on shard 2. I might switch shards and see if i get a different result.

**Comment by frode88** [comment]
> > > > Finaly! thank you alot! now i search and find my adress. so every adress have to have balance to show on explorer:)
> > > 
> > > 
> > > That's correct. I dealt with the same issue early on.
> > 
> > 
> > Can I ask you what you use(vps, wich cpu) to mine? im running 8 core 24hours and no reward..:S
> 
> I was using multiple VPS (24 core) and a bare metal server (8 core) early in the process. once mining started having issues, I switched to my desktop. It started out OK. The past couple of weeks have been awful though. I literally got 1 block after several days today. Not sure if it's the shard or what. I primarily mine on shard 2. I might switch shards and see if i get a different result.

ok, thank you. mining on shard 1 - no luck there:(

**Comment by frode88** [comment]
i wonder if someone got gpu miner working? like they did with QKC. They took over the chain!

**Comment by frode88** [comment]
btw do you remember the diff when reward was ok?

**Comment by troytrojan01** [comment]
> btw do you remember the diff when reward was ok?

The difficulty did increase by about ~30%, but the rewards seem to take much more than a 30% hit. It's probably a combination of difficulty, syncing issues, & possibly someone figured out how to leverage a GPU.

**Comment by frode88** [comment]
> > btw do you remember the diff when reward was ok?
> 
> The difficulty did increase by about ~30%, but the rewards seem to take much more than a 30% hit. It's probably a combination of difficulty, syncing issues, & possibly someone figured out how to leverage a GPU.

ok, thank you for all info:)

**Comment by troytrojan01** [comment]
> > > btw do you remember the diff when reward was ok?
> > 
> > 
> > The difficulty did increase by about ~30%, but the rewards seem to take much more than a 30% hit. It's probably a combination of difficulty, syncing issues, & possibly someone figured out how to leverage a GPU.
> 
> ok, thank you for all info:)

No problem.

**Comment by shawnxin89** [comment]
> I raised the issue about the hashrate command a while back. No action taken on it.
> 
> [#1015 (comment)](https://github.com/seeleteam/go-seele/issues/1015#issue-500527714)


Our mining algorithm doesn't depend on hash computation. Therefore we didn't provide it in the api.

**Comment by shawnxin89** [comment]
> HI.
> one more thing. why miner hashrate dosent work?
> 
> root@vultr:~/go/src/github.com/seeleteam/go-seele/build# ./client miner hashrate -a 127.0.0.1:8027
> 2019/11/24 16:00:00 Failed to call rpc, The method miner_getHashrate does not exist/is not available


Our mining algorithm doesn't rely on hash computation so much. Therefore we didn't provide it in the api.

**Comment by frode88** [comment]
> > HI.
> > one more thing. why miner hashrate dosent work?
> > root@vultr:~/go/src/github.com/seeleteam/go-seele/build# ./client miner hashrate -a 127.0.0.1:8027
> > 2019/11/24 16:00:00 Failed to call rpc, The method miner_getHashrate does not exist/is not available
> 
> Our mining algorithm doesn't rely on hash computation so much. Therefore we didn't provide it in the api.

Hi.
Can you tell me how it works? why others get more block then other people?

**Comment by lkbtboy** [comment]
I have same issue.
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x78171f8bfd450b0f2be27ff60243e896f7eb43060b790a96b0c89faa1efa83d1" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
xf5aeffb413847b360e8855b5649806c206ba9b7732f017973a8c944e27119b04" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
xf0c1c3d957de27d8a5e4f75e8ef50348830e1de223822339a1b3938753be65ff" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x6dca228f7a2141b6d5a83c6863b347008746aa0525e66e8e8dd07fb7e47b2eba" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
xa4aa96560178ed483cf6d27d2cae7b3072fe0563922a39dd3e47f16ed1239378" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x0d16f9300b2aecfbc1f90ae1791e7de37865dd8253f7acdba3fc6f720493454e" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x9e295266526fc7916f4e86535fe309ec7894f6ba1b85c25ea0614f22ec6e9867" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x5333d5c062057fb565a89b058dc4f3d0f4be9daedd05510b6332bb7d3880ca68" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x5293adcd099558940c207907c5c93e9787ed67d87326a03f25af35d6e7c99d53" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
xead531d9cb99482c8ed2be3b322d0afbf0680087e9d2c7831c4d17453a1c83d5" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x58ce94901aa6c6b8498beda0e798cd0c648455d715568fbb5b70bc1e2340f976" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x8fa6cae84eed0772a2fb25d89ddb37f253e268e1584af8fe0f605303ad8d519e" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x5f7bd5011c8f2d99331c1184926ea6558b235ccfd2c63af1c8faa900277f20d3" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x1bdcd1ae1a4622a0f36fb1fa771ae066647cda3ee487e96113dc4dcc8c598f20" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x127f545ad06bc95f3c15415b95b253250c06c20a9cc7113978e8fde6c57f32e5" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x6332a44129109916f8638a9d649e6a33289fa3470d16576330696128646273e3" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
xd379b6cc96b25803f81890b694fd60dbb37988c4ae2fa2e1f2581614bc3f2c8a" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x0f68f4a18b305112c343054432e86e20da86cdb7a1f38315ff2ea37b1d84176b" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
xb371af317de6288aa22ebaeacdec28f2b46eec1fe396900652681967e507928f" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x44509554531e85ef2482cf3c9e26f4dfe1cb9ed947cefde51ae0b8eb271a7964" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x2a1414600153fa4fc9163dcd51ddb2cfa6254945df1e91996368f56877dd6903" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x8ae42ced3b90a97d092a21dc56e3610fc1e944aa506c0eda776139a5b6aaf369" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
xe2cab8974a89bb9d45ca86801ee2338dc5b175c791371b41a2b96729e2d66c1f" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x70a6e1b0e6a82a291096ca8c9e96e986ba09fc184943d598903be8d5278d1fc9" caller="task.go:92" module=miner
seele_1  | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
x1deed88c6661586044dd34c514915ec84f38f83bd0b164a139056a2656c8bd8b" caller="task.go:92" module=miner

**Comment by shawnxin89** [comment]
> > > HI.
> > > one more thing. why miner hashrate dosent work?
> > > root@vultr:~/go/src/github.com/seeleteam/go-seele/build# ./client miner hashrate -a 127.0.0.1:8027
> > > 2019/11/24 16:00:00 Failed to call rpc, The method miner_getHashrate does not exist/is not available
> > 
> > 
> > Our mining algorithm doesn't rely on hash computation so much. Therefore we didn't provide it in the api.
> 
> Hi.
> Can you tell me how it works? why others get more block then other people?



> I have same issue.
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x78171f8bfd450b0f2be27ff60243e896f7eb43060b790a96b0c89faa1efa83d1" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> xf5aeffb413847b360e8855b5649806c206ba9b7732f017973a8c944e27119b04" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> xf0c1c3d957de27d8a5e4f75e8ef50348830e1de223822339a1b3938753be65ff" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x6dca228f7a2141b6d5a83c6863b347008746aa0525e66e8e8dd07fb7e47b2eba" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> xa4aa96560178ed483cf6d27d2cae7b3072fe0563922a39dd3e47f16ed1239378" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x0d16f9300b2aecfbc1f90ae1791e7de37865dd8253f7acdba3fc6f720493454e" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x9e295266526fc7916f4e86535fe309ec7894f6ba1b85c25ea0614f22ec6e9867" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x5333d5c062057fb565a89b058dc4f3d0f4be9daedd05510b6332bb7d3880ca68" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x5293adcd099558940c207907c5c93e9787ed67d87326a03f25af35d6e7c99d53" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> xead531d9cb99482c8ed2be3b322d0afbf0680087e9d2c7831c4d17453a1c83d5" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x58ce94901aa6c6b8498beda0e798cd0c648455d715568fbb5b70bc1e2340f976" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x8fa6cae84eed0772a2fb25d89ddb37f253e268e1584af8fe0f605303ad8d519e" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x5f7bd5011c8f2d99331c1184926ea6558b235ccfd2c63af1c8faa900277f20d3" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x1bdcd1ae1a4622a0f36fb1fa771ae066647cda3ee487e96113dc4dcc8c598f20" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x127f545ad06bc95f3c15415b95b253250c06c20a9cc7113978e8fde6c57f32e5" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x6332a44129109916f8638a9d649e6a33289fa3470d16576330696128646273e3" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> xd379b6cc96b25803f81890b694fd60dbb37988c4ae2fa2e1f2581614bc3f2c8a" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x0f68f4a18b305112c343054432e86e20da86cdb7a1f38315ff2ea37b1d84176b" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> xb371af317de6288aa22ebaeacdec28f2b46eec1fe396900652681967e507928f" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x44509554531e85ef2482cf3c9e26f4dfe1cb9ed947cefde51ae0b8eb271a7964" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x2a1414600153fa4fc9163dcd51ddb2cfa6254945df1e91996368f56877dd6903" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x8ae42ced3b90a97d092a21dc56e3610fc1e944aa506c0eda776139a5b6aaf369" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> xe2cab8974a89bb9d45ca86801ee2338dc5b175c791371b41a2b96729e2d66c1f" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x70a6e1b0e6a82a291096ca8c9e96e986ba09fc184943d598903be8d5278d1fc9" caller="task.go:92" module=miner
> seele_1 | time="2019-11-22T11:49:38+08:00" level=warning msg="apply debt error debt already packed, debt hash 0
> x1deed88c6661586044dd34c514915ec84f38f83bd0b164a139056a2656c8bd8b" caller="task.go:92" module=miner

It is safe to ignore it. It means this debt has been packed on chain. Not an error.

**Comment by frode88** [comment]
> > > > btw do you remember the diff when reward was ok?
> > > 
> > > 
> > > The difficulty did increase by about ~30%, but the rewards seem to take much more than a 30% hit. It's probably a combination of difficulty, syncing issues, & possibly someone figured out how to leverage a GPU.
> > 
> > 
> > ok, thank you for all info:)
> 
> No problem.

Hi. I have Q. Do you use windows wallet to send Seele? thank you.

**Comment by frode88** [comment]
@shawnxin89 Hi. everytime i start the node i get this erro. should i just ignore it?

![olol](https://user-images.githubusercontent.com/22121200/69635491-cf556980-1054-11ea-84ae-d98c846a82d6.PNG)

**Comment by troytrojan01** [comment]
Yes. Windows wallet

**Comment by frode88** [comment]
> Yes. Windows wallet
> […](#)
> Sent from my iPhone
> On Nov 26, 2019, at 2:27 AM, frode88 ***@***.***> wrote: ﻿ btw do you remember the diff when reward was ok? The difficulty did increase by about ~30%, but the rewards seem to take much more than a 30% hit. It's probably a combination of difficulty, syncing issues, & possibly someone figured out how to leverage a GPU. ok, thank you for all info:) No problem. Hi. I have Q. Do you use windows wallet to send Seele? thank you. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

thank you.
