### ISSUE TITLE
"printLog": true

### ISSUE THREAD

**Issue by frode88** [seeleteam/go-seele#1060]
Hi.
Where the node keep the log of the node? I just cant find it. thank you

**Comment by shawnxin89** [comment]
> Hi.
> Where the node keep the log of the node? I just cant find it. thank you

The log is not automatically saved in the disk. You can do that by yourself.

**Comment by frode88** [comment]
> > Hi.
> > Where the node keep the log of the node? I just cant find it. thank you
> 
> The log is not automatically saved in the disk. You can do that by yourself.

can you give me the line that can save it on any folder? thank you
