### ISSUE TITLE
Look at this erro and node go offline.

### ISSUE THREAD

**Issue by frode88** [seeleteam/go-seele#1063]
![nodedie](https://user-images.githubusercontent.com/22121200/69881863-a04a2c80-12ce-11ea-914d-d43320586026.PNG)

**Comment by Jimjimini** [comment]
yes receiving that error as well, mining it seems is broken, a huge decrease in nodes being run, we need a fix quickly, the team should prioritise this, not the sub chains.

**Comment by frode88** [comment]
![Skjermbilde](https://user-images.githubusercontent.com/22121200/69893527-cdb8c980-1312-11ea-8528-f1f29ed12080.PNG)
