### ISSUE TITLE
transferred seele，but not received seele in my account

### ISSUE THREAD

**Issue by 1994jeff** [seeleteam/go-seele#1065]
I transferred seele tokens from Huobi Global to my account. Why haven't I received them? It's been a day so far. Contact Huobi customer service to say that the block has confirmed that the transfer was successful yesterday.
My account address is as follows: 0xc6f0d90f8f513a64d9b121fbd06a6edc3e9830e1

**Comment by frode88** [comment]
> Huobi Global

Huobi Global  uses ERC Token. SO if you sendt thos coin to mainnet adress.. they are lost for ever

**Comment by troytrojan01** [comment]
> I transferred seele tokens from Huobi Global to my account. Why haven't I received them? It's been a day so far. Contact Huobi customer service to say that the block has confirmed that the transfer was successful yesterday.
> My account address is as follows: 0xc6f0d90f8f513a64d9b121fbd06a6edc3e9830e1

The tokens are in the wallet
![75CA0269-1D0B-4E51-9C2C-087C339D7C86](https://user-images.githubusercontent.com/39805603/69933193-768e3280-1493-11ea-8800-dd46e91bcb93.png)

**Comment by 1994jeff** [comment]
> > I transferred seele tokens from Huobi Global to my account. Why haven't I received them? It's been a day so far. Contact Huobi customer service to say that the block has confirmed that the transfer was successful yesterday.
> > My account address is as follows: 0xc6f0d90f8f513a64d9b121fbd06a6edc3e9830e1
> 
> The tokens are in the wallet
> ![75CA0269-1D0B-4E51-9C2C-087C339D7C86](https://user-images.githubusercontent.com/39805603/69933193-768e3280-1493-11ea-8800-dd46e91bcb93.png)

Well, thank you for answering, I thought it would be sufficient to fill in the seele account address directly in Huobi Global. Looks like I have lost these coins, right? So what do I need to do to transfer seele coins from Huobi Global to seele ’s official wallet?

**Comment by frode88** [comment]
> > > I transferred seele tokens from Huobi Global to my account. Why haven't I received them? It's been a day so far. Contact Huobi customer service to say that the block has confirmed that the transfer was successful yesterday.
> > > My account address is as follows: 0xc6f0d90f8f513a64d9b121fbd06a6edc3e9830e1
> > 
> > 
> > The tokens are in the wallet
> > ![75CA0269-1D0B-4E51-9C2C-087C339D7C86](https://user-images.githubusercontent.com/39805603/69933193-768e3280-1493-11ea-8800-dd46e91bcb93.png)
> 
> Well, thank you for answering, I thought it would be sufficient to fill in the seele account address directly in Huobi Global. Looks like I have lost these coins, right? So what do I need to do to transfer seele coins from Huobi Global to seele ’s official wallet?

Tbh, you need to learn different between erc token and nativ toke :) yes they are lost. luckey you didnt send much coin.

**Comment by 1994jeff** [comment]
> > I transferred seele tokens from Huobi Global to my account. Why haven't I received them? It's been a day so far. Contact Huobi customer service to say that the block has confirmed that the transfer was successful yesterday.
> > My account address is as follows: 0xc6f0d90f8f513a64d9b121fbd06a6edc3e9830e1
> 
> The tokens are in the wallet
> ![75CA0269-1D0B-4E51-9C2C-087C339D7C86](https://user-images.githubusercontent.com/39805603/69933193-768e3280-1493-11ea-8800-dd46e91bcb93.png)

Well, thank you for answering, I thought it would be sufficient to fill in the seele account address directly in Huobi Global. Looks like I have lost these coins, right? So what do I need to do to transfer seele coins from Huobi Global to seele ’s official wallet?

> > > > I transferred seele tokens from Huobi Global to my account. Why haven't I received them? It's been a day so far. Contact Huobi customer service to say that the block has confirmed that the transfer was successful yesterday.
> > > > My account address is as follows: 0xc6f0d90f8f513a64d9b121fbd06a6edc3e9830e1
> > > 
> > > 
> > > The tokens are in the wallet
> > > ![75CA0269-1D0B-4E51-9C2C-087C339D7C86](https://user-images.githubusercontent.com/39805603/69933193-768e3280-1493-11ea-8800-dd46e91bcb93.png)
> > 
> > 
> > Well, thank you for answering, I thought it would be sufficient to fill in the seele account address directly in Huobi Global. Looks like I have lost these coins, right? So what do I need to do to transfer seele coins from Huobi Global to seele ’s official wallet?
> 
> Tbh, you need to learn different between erc token and nativ toke :) yes they are lost. luckey you didnt send much coin.

Yes, because I don't know much about blockchain and this field, so I just tried to transfer a little coin, thank you for your answer.
