### ISSUE TITLE
failed to validate debt via verifier

### ISSUE THREAD

**Issue by frode88** [seeleteam/go-seele#1068]
Hi.
what is this erro?

![Skjermbilde](https://user-images.githubusercontent.com/22121200/70080879-ab22fb00-1607-11ea-9f42-2ba52cb26926.PNG)

**Comment by frode88** [comment]
![Skjermbilde](https://user-images.githubusercontent.com/22121200/70178425-906e8600-16dc-11ea-8799-9519e0fe75a3.PNG)

**Comment by 1994jeff** [comment]
I always get this error

**Comment by frode88** [comment]
> I always get this error

Do you get any blocks?
