### ISSUE TITLE
nodes lost connections with shard4

### ISSUE THREAD

**Issue by frode88** [seeleteam/go-seele#1075]
![Skjermbilde](https://user-images.githubusercontent.com/22121200/70726951-274fc980-1cff-11ea-9536-5c32c3003e6e.PNG)
from what i understand it- node need to be connected to all shard to confirm a block.. or im wrong? most of the time 0 connections to shard4..

**Comment by shawnxin89** [comment]
> ![Skjermbilde](https://user-images.githubusercontent.com/22121200/70726951-274fc980-1cff-11ea-9536-5c32c3003e6e.PNG)
> from what i understand it- node need to be connected to all shard to confirm a block.. or im wrong? most of the time 0 connections to shard4..

Generally the node works best with connections to all shards. But it can still confirm a block if the  block doesn't include cross-shard txs(debts) from shard 4.

**Comment by frode88** [comment]
> > ![Skjermbilde](https://user-images.githubusercontent.com/22121200/70726951-274fc980-1cff-11ea-9536-5c32c3003e6e.PNG)
> > from what i understand it- node need to be connected to all shard to confirm a block.. or im wrong? most of the time 0 connections to shard4..
> 
> Generally the node works best with connections to all shards. But it can still confirm a block if the block doesn't include cross-shard txs(debts) from shard 4.

thank you for fast answer:) one last Q. when i add my nodes on shard4 manuly to node.json. they dosent show on othr nodes like my nodes on shard2? even dosent show on explorer after days of running. any ideas? there is any benefit to run discorvery?

**Comment by shawnxin89** [comment]
> > > ![Skjermbilde](https://user-images.githubusercontent.com/22121200/70726951-274fc980-1cff-11ea-9536-5c32c3003e6e.PNG)
> > > from what i understand it- node need to be connected to all shard to confirm a block.. or im wrong? most of the time 0 connections to shard4..
> > 
> > 
> > Generally the node works best with connections to all shards. But it can still confirm a block if the block doesn't include cross-shard txs(debts) from shard 4.
> 
> thank you for fast answer:) one last Q. when i add my nodes on shard4 manuly to node.json. they dosent show on othr nodes like my nodes on shard2? even dosent show on explorer after days of running. any ideas? there is any benefit to run discorvery?

You mean adding your node to the static nodes? Static nodes may bring your node more connections in an indirect way. But your node doesn't always handshake with static nodes directly. Explorer only shows the nodes ever connected to its own node.

**Comment by frode88** [comment]
> > > > ![Skjermbilde](https://user-images.githubusercontent.com/22121200/70726951-274fc980-1cff-11ea-9536-5c32c3003e6e.PNG)
> > > > from what i understand it- node need to be connected to all shard to confirm a block.. or im wrong? most of the time 0 connections to shard4..
> > > 
> > > 
> > > Generally the node works best with connections to all shards. But it can still confirm a block if the block doesn't include cross-shard txs(debts) from shard 4.
> > 
> > 
> > thank you for fast answer:) one last Q. when i add my nodes on shard4 manuly to node.json. they dosent show on othr nodes like my nodes on shard2? even dosent show on explorer after days of running. any ideas? there is any benefit to run discorvery?
> 
> You mean adding your node to the static nodes? Static nodes may bring your node more connections in an indirect way. But your node doesn't always handshake with static nodes directly. Explorer only shows the nodes ever connected to its own node.

Hi. No I added the snode direct to node.json in .seele folder. so I have node on shard 4 and 2. So i wanted them to add each other so I manuly added them in the node.sjon file and still dont see each other.  There is anyway I can make my nodes to see each other? so they have stabel connetion all the time ?

**Comment by shawnxin89** [comment]
> > > > > ![Skjermbilde](https://user-images.githubusercontent.com/22121200/70726951-274fc980-1cff-11ea-9536-5c32c3003e6e.PNG)
> > > > > from what i understand it- node need to be connected to all shard to confirm a block.. or im wrong? most of the time 0 connections to shard4..
> > > > 
> > > > 
> > > > Generally the node works best with connections to all shards. But it can still confirm a block if the block doesn't include cross-shard txs(debts) from shard 4.
> > > 
> > > 
> > > thank you for fast answer:) one last Q. when i add my nodes on shard4 manuly to node.json. they dosent show on othr nodes like my nodes on shard2? even dosent show on explorer after days of running. any ideas? there is any benefit to run discorvery?
> > 
> > 
> > You mean adding your node to the static nodes? Static nodes may bring your node more connections in an indirect way. But your node doesn't always handshake with static nodes directly. Explorer only shows the nodes ever connected to its own node.
> 
> Hi. No I added the snode direct to node.json in .seele folder. so I have node on shard 4 and 2. So i wanted them to add each other so I manuly added them in the node.sjon file and still dont see each other. There is anyway I can make my nodes to see each other? so they have stabel connetion all the time ?

At this moment, our code don't have this function. The nodes are picked randomly from the node set to connect.

**Comment by frode88** [comment]
> > > > > > ![Skjermbilde](https://user-images.githubusercontent.com/22121200/70726951-274fc980-1cff-11ea-9536-5c32c3003e6e.PNG)
> > > > > > from what i understand it- node need to be connected to all shard to confirm a block.. or im wrong? most of the time 0 connections to shard4..
> > > > > 
> > > > > 
> > > > > Generally the node works best with connections to all shards. But it can still confirm a block if the block doesn't include cross-shard txs(debts) from shard 4.
> > > > 
> > > > 
> > > > thank you for fast answer:) one last Q. when i add my nodes on shard4 manuly to node.json. they dosent show on othr nodes like my nodes on shard2? even dosent show on explorer after days of running. any ideas? there is any benefit to run discorvery?
> > > 
> > > 
> > > You mean adding your node to the static nodes? Static nodes may bring your node more connections in an indirect way. But your node doesn't always handshake with static nodes directly. Explorer only shows the nodes ever connected to its own node.
> > 
> > 
> > Hi. No I added the snode direct to node.json in .seele folder. so I have node on shard 4 and 2. So i wanted them to add each other so I manuly added them in the node.sjon file and still dont see each other. There is anyway I can make my nodes to see each other? so they have stabel connetion all the time ?
> 
> At this moment, our code don't have this function. The nodes are picked randomly from the node set to connect.

Thank you and have a Nice day.
