### ISSUE TITLE
panic: hex string without 0x prefix

### ISSUE THREAD

**Issue by Rickyose** [seeleteam/go-seele#1076]
Guys can someone help

i try to mining and using download without need to build (this link https://github.com/seeleteam/go-seele/releases/download/v1.2.6/linux_v1.2.6.zip) 

but when i got step 

`./node start –c ../cmd/node/config/node1.json — threads 50`

which i modified to:

`./node start -c ../node1.json — threads 7 `

i got errror 

```
panic: hex string without 0x prefix
github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).execute(0x13be800, 0xc0000c2690, 0x5, 0x5, 0x13be800, 0xc0000c2690) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:757 +0x2cc github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13be5a0, 0xc000175f68, 0xaa7991, 0x13bea60) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:843 +0x2fd github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).Execute(0x13be5a0, 0x1, 0xc000175f88) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:791 +0x2b github.com/seeleteam/go-seele/cmd/node/cmd.Execute() /root/go/src/github.com/seeleteam/go-seele/cmd/node/cmd/root.go:38 +0x31 main.main() /root/go/src/github.com/seeleteam/go-seele/cmd/node/main.go:11 +0x20
```

**Comment by shawnxin89** [comment]
> Guys can someone help
> 
> i try to mining and using download without need to build (this link https://github.com/seeleteam/go-seele/releases/download/v1.2.6/linux_v1.2.6.zip)
> 
> but when i got step
> 
> `./node start –c ../cmd/node/config/node1.json — threads 50`
> 
> which i modified to:
> 
> `./node start -c ../node1.json — threads 7 `
> 
> i got errror
> 
> ```
> panic: hex string without 0x prefix
> github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).execute(0x13be800, 0xc0000c2690, 0x5, 0x5, 0x13be800, 0xc0000c2690) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:757 +0x2cc github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13be5a0, 0xc000175f68, 0xaa7991, 0x13bea60) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:843 +0x2fd github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).Execute(0x13be5a0, 0x1, 0xc000175f88) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:791 +0x2b github.com/seeleteam/go-seele/cmd/node/cmd.Execute() /root/go/src/github.com/seeleteam/go-seele/cmd/node/cmd/root.go:38 +0x31 main.main() /root/go/src/github.com/seeleteam/go-seele/cmd/node/main.go:11 +0x20
> ```

Do you modified node1.json following the tutorial? If yes, maybe use --threads 7 instead of -threads 7.

**Comment by Rickyose** [comment]
> 
> 
> > Guys can someone help
> > i try to mining and using download without need to build (this link https://github.com/seeleteam/go-seele/releases/download/v1.2.6/linux_v1.2.6.zip)
> > but when i got step
> > `./node start –c ../cmd/node/config/node1.json — threads 50`
> > which i modified to:
> > `./node start -c ../node1.json — threads 7 `
> > i got errror
> > ```
> > panic: hex string without 0x prefix
> > github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).execute(0x13be800, 0xc0000c2690, 0x5, 0x5, 0x13be800, 0xc0000c2690) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:757 +0x2cc github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13be5a0, 0xc000175f68, 0xaa7991, 0x13bea60) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:843 +0x2fd github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra.(*Command).Execute(0x13be5a0, 0x1, 0xc000175f88) /root/go/src/github.com/seeleteam/go-seele/vendor/github.com/spf13/cobra/command.go:791 +0x2b github.com/seeleteam/go-seele/cmd/node/cmd.Execute() /root/go/src/github.com/seeleteam/go-seele/cmd/node/cmd/root.go:38 +0x31 main.main() /root/go/src/github.com/seeleteam/go-seele/cmd/node/main.go:11 +0x20
> > ```
> 
> Do you modified node1.json following the tutorial? If yes, maybe use --threads 7 instead of -threads 7.

Yes, seems somehow i put address in wrong format, so i doing it again and its work well. thank you for your help
