### ISSUE TITLE
recoveryPoint.json: too many open files  

### ISSUE THREAD

**Issue by frode88** [seeleteam/go-seele#1084]
Hi. I change file limit to 1M and still get this. any idea how to solve this? thank you

Failed to write recovery point JSON data to file, file = /root/.seele/node1/recoveryPoint.json, error = open /root/.seele/node1/recoveryPoint.json: too many open files  caller="blockchain_recover.go:137" module=recoveryPoint

**Comment by shawnxin89** [comment]
> Hi. I change file limit to 1M and still get this. any idea how to solve this? thank you
> 
> Failed to write recovery point JSON data to file, file = /root/.seele/node1/recoveryPoint.json, error = open /root/.seele/node1/recoveryPoint.json: too many open files caller="blockchain_recover.go:137" module=recoveryPoint

The solution depends on your operating system. You need to pick the correct one.

**Comment by frode88** [comment]
wich os you recomand? i tested cent os, alpine and ubuntu.
