### ISSUE TITLE
Core /Tech Team

### ISSUE THREAD

**Issue by Drmaolinzheng** [seeleteam/go-seele#1114]
Hello this is Dr Maolin Zheng i have come a long way with you guys after the Foundation team left After ICO but they are back now and they have Major shares. I need you guys  to help me so we don't lose the Seele name and logo 

您好，我是郑茂林博士。在基金会团队离开ICO之后，你们与大家取得了长足的合作，但他们又回来了，他们拥有主要股份。我需要你们帮助我，这样我们就不会失去Seele的名称和徽标

0x5305df5a0fb2c6be89ff2fd393bc6c1b5e958919

**Comment by dannyboyuk73** [comment]
SPAM / SCAM / IGNORE

**Comment by Wei-Bi** [comment]
I stand with Dr Zheng 
Foundation team is trying to manipulate him

**Comment by Drmaolinzheng** [comment]
> I stand with Dr Zheng
> Foundation team is trying to manipulate him

Thank you Dr Wei Bi

**Comment by muyiy** [comment]
SPAM
