### ISSUE TITLE
deploy contract to address that has sufiiicient balance,but return insufficient balance

### ISSUE THREAD

**Issue by Qsnh** [seeleteam/go-seele#514]
address balance:

```
xiaoteng@xiaoteng-PC:~/go/src/github.com/seeleteam/go-seele/cmd/client$ ./client getbalance
{
	"Account": "0x7be3ba491c10dffd425da61f35b2c7f750e91161",
	"Balance": 673499997900
}
```

deploy contract:

```
xiaoteng@xiaoteng-PC:~/go/src/github.com/seeleteam/go-seele/cmd/vm$ ./vm create -c 0x608060405234801561001057600080fd5b5060bf8061001f6000396000f30060806040526004361060485763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166360fe47b18114604d5780636d4ce63c146064575b600080fd5b348015605857600080fd5b5060626004356088565b005b348015606f57600080fd5b506076608d565b60408051918252519081900360200190f35b600055565b600054905600a165627a7a72305820f212b09e65e4f4c89d0cdb1792305d7cfeb85d7693a25230040bdbabab634bc60029 -a 0x7be3ba491c10dffd425da61f35b2c7f750e91161
Failed to create contract, insufficient balance for transfer
```

**Comment by wangff15386** [comment]
The vm is a locally built virtual machine that tests whether a smart contract works as expected, which means it is separate from the blockchain.
Therefore, using a blockchain account to test a contract in vm must not work.
The vm itself has a command `new` and `set` to create an account and set the balance, please use it. See the wiki for more details.

**Comment by Qsnh** [comment]
i see.but has another question,the contract addres is belong random shard,et shard1,shard2...but my local node only run one shard1,so how can i chioce a shard num when deploy contract address?

**Comment by wangff15386** [comment]
Since your from address is a random shard, just use the usual `node key --shard 1` to generate the address from the account.
![image](https://user-images.githubusercontent.com/35793667/45024564-eb45a780-b06b-11e8-9474-8440d4b60ada.png)

**Comment by Qsnh** [comment]
thx :+1: . how deploy contract to blockchain?

**Comment by wangff15386** [comment]
See the `sendtx` command, just let the `to` is empty.
![image](https://user-images.githubusercontent.com/35793667/45025132-3f9d5700-b06d-11e8-8cbc-c7f340bc687a.png)

**Comment by Qsnh** [comment]
i will try. thx :smile:

**Comment by Qsnh** [comment]
and payload is contract code by solc transform?

**Comment by wangff15386** [comment]
Yes it is, now we can use the evm contract directly, so you should compile it first in solc.

**Comment by Qsnh** [comment]
i see.
