### ISSUE TITLE
deployed contract address

### ISSUE THREAD

**Issue by Qsnh** [seeleteam/go-seele#520]
xiaoteng@xiaoteng-PC:~/go/src/github.com/seeleteam/go-seele/cmd/client$ ./client sendtx --from keyfile/shard14 --amount 0 --fee 1 --payload 0x608060405234801561001057600080fd5b5060bf8061001f6000396000f30060806040526004361060485763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166360fe47b18114604d5780636d4ce63c146064575b600080fd5b348015605857600080fd5b5060626004356088565b005b348015606f57600080fd5b506076608d565b60408051918252519081900360200190f35b600055565b600054905600a165627a7a72305820f212b09e65e4f4c89d0cdb1792305d7cfeb85d7693a25230040bdbabab634bc60029
Please input your key file password: 
account 0x7be3ba491c10dffd425da61f35b2c7f750e91161 current nonce: 6, sending nonce: 6
transaction sent successfully
{
    "Hash": "0x4e039e4329eec54ea48660a15eca49e360e5223167cb5c16aba9320b1c1640da",
    "Data": {
        "From": "0x7be3ba491c10dffd425da61f35b2c7f750e91161",
        "To": "0x0000000000000000000000000000000000000000",
        "Amount": 0,
        "AccountNonce": 6,
        "Fee": 1,
        "Timestamp": 0,
        "Payload": "0x608060405234801561001057600080fd5b5060bf8061001f6000396000f30060806040526004361060485763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166360fe47b18114604d5780636d4ce63c146064575b600080fd5b348015605857600080fd5b5060626004356088565b005b348015606f57600080fd5b506076608d565b60408051918252519081900360200190f35b600055565b600054905600a165627a7a72305820f212b09e65e4f4c89d0cdb1792305d7cfeb85d7693a25230040bdbabab634bc60029"
    },
    "Signature": {
        "Sig": "vqjqSR2eHDBkn/bMnR7WSjA4914wcXu5pGCd3+mWBwokOyW+m0JM81NYdCaPqbadVe/2bjZ6nulskr7sCsKW+wE="
    }
}

how can i get contract address?

**Comment by wangff15386** [comment]
See the wiki:
https://github.com/seeleteam/go-seele/wiki/API-Document#getreceiptbytxhash

**Comment by Qsnh** [comment]
yes. :smile: 

```
xiaoteng@xiaoteng-PC:~/go/src/github.com/seeleteam/go-seele/cmd/client$ ./client getreceipt --hash 0x4e039e4329eec54ea48660a15eca49e360e5223167cb5c16aba9320b1c1640da
{
	"contract": "0x8a9e48f30cd97667a741bf7446882827a52000b2",
	"failed": false,
	"poststate": "0x3ae0eb3a932cc6ff4a383183f77349f64c881495c968fb3c21738bf721bbbb87",
	"result": "0x60806040526004361060485763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166360fe47b18114604d5780636d4ce63c146064575b600080fd5b348015605857600080fd5b5060626004356088565b005b348015606f57600080fd5b506076608d565b60408051918252519081900360200190f35b600055565b600054905600a165627a7a72305820f212b09e65e4f4c89d0cdb1792305d7cfeb85d7693a25230040bdbabab634bc60029",
	"txhash": "0x4e039e4329eec54ea48660a15eca49e360e5223167cb5c16aba9320b1c1640da"
}
```

but i use `getreceipt` not `getreceiptbytxhash`
