### ISSUE TITLE
how to generate signature?

### ISSUE THREAD

**Issue by Qsnh** [seeleteam/go-seele#524]
keyfile:

```json
{
	"version": 1,
	"address": "0x7be3ba491c10dffd425da61f35b2c7f750e91161",
	"crypto": {
		"ciphertext": "0f481bd102f3b9ec8aa87aa0e62a7aad2430c459a962c2e945974d3983e69de0",
		"iv": "57ff12709954f019021bf600f3c6ab68",
		"salt": "12861d0e229cde4a1bca5be359dc607c07f23de23b009e29cda404e8297865c5",
		"mac": "0x58b58a34332facf7fd4a899e7770b6ca76d62b704a0d72cce0956d41dba0b019"
	}
}
```

and password: `123456`, how to generate signature to use sendtx?

**Comment by wangff15386** [comment]
If you use the seele `client sendtx` command, the signature will be processed automatically, otherwise if you use seele rpc, you should sign tx with your own program, such as calling `client sign`

**Comment by Qsnh** [comment]
```
xiaoteng@xiaoteng-PC:~/go/src/github.com/seeleteam/go-seele/cmd/client$ ./client sign -h
NAME:
   client sign - generate a signed transaction and print it out

USAGE:
   client sign [command options] [arguments...]

OPTIONS:
   --address value, -a value  address for client to request (default: "127.0.0.1:8027")
   --privatekey value         private key for account
   --to value                 to address
   --amount value             amount value, unit is fan
   --fee value                transaction fee
   --payload value            transaction payload info
   --nonce value              transaction nonce (default: 0)
```

the `privatekey` is?

`node key` command will return privatekey,but how get privatekey from keyfile

**Comment by wangff15386** [comment]
`client savekey`

**Comment by Qsnh** [comment]
now I have a keyfile and password, how do I get the signature, because the rpc needs to pass the sinagure? `client savekey` is generate keyfile by privatekey. :cry:

**Comment by wangff15386** [comment]
The test network did not open this function, and I will increase it later. The account you generated locally can also be used on the test web. 
And you also can use https://web-wallet.seele.pro/#/SendSEELE this faucet account to transfer money to your locally generated account.

**Comment by Qsnh** [comment]
good :+1:
