### ISSUE TITLE
The method txpool_getReceiptByTxHash does not exist/is not available

### ISSUE THREAD

**Issue by Qsnh** [seeleteam/go-seele#527]
![image](https://user-images.githubusercontent.com/12671205/45150374-47d8cc00-b1fe-11e8-9ba6-8322d2d284c1.png)

**Comment by wangff15386** [comment]
The txpool method is private, it is temporarily blocked on the master branch and will be opened later.
Now you can use `client getreceipt` command.

**Comment by Qsnh** [comment]
ok
