### ISSUE TITLE
How does the meta blockchain manage the subchain?

### ISSUE THREAD

**Issue by cristicmf** [seeleteam/go-seele#81]
How does the meta blockchain manage the subchain?
How to reach a consensus？

**Comment by WTer** [comment]
Hi, cristicmf 

For the first question, you can refer to section 5.4 of whitepaper for more detail
(https://s3.ap-northeast-2.amazonaws.com/wp.s3.seele.pro/Seele_tech_whitepaper_EN_v1.9.pdf).

About how to reach a consensus, I just make a quick introduction:
During the first round of the block consensus process by using our EDA algorithm, a group of nodes is randomly selected as block producer candidates according to the contribution of each node (received and processed consensus requests), then the pBFT algorithm is used to choose the final node producer.

**Comment by cristicmf** [comment]
I am not talking about the  consensus  process node, I just want know the "meta blockchain manage the subchain".
