### ISSUE TITLE
主网什么时候发布，为什么都好几天没更新代码了？

### ISSUE THREAD

**Issue by Aoseala** [seeleteam/go-seele#885]

**Comment by Aoseala** [comment]
英文周报也两期没发了

**Comment by WTer** [comment]
周报一直在更新的，每周三发上一周的周报。
最近一周的周报：https://medium.com/seeletech/seele-weekly-report-28-d6fc07de9f0e
历史周报：https://medium.com/seeletech

**Comment by Aoseala** [comment]
> 周报一直在更新的，每周三发上一周的周报。
> 最近一周的周报：https://medium.com/seeletech/seele-weekly-report-28-d6fc07de9f0e
> 历史周报：https://medium.com/seeletec

**Comment by Aoseala** [comment]
好的  谢谢  推特上没看到发推
