### ISSUE TITLE
Did you abandon the Seele token (ie. exit scam)?

### ISSUE THREAD

**Issue by luke1allison** [seeleteam/go-seele#898]
From a member of your Telegram community that you abandoned:

"They had abandoned their token, the Seele dev team found other financial funds in Beijing and leave their token to others, some marketing team members had moved.  I don't know if some big whale doing pump and dump things in future. in value investing, I am afraid its a failed project"

**Comment by LincolnZeng** [comment]
Our tech team are working hard on this project. Recently, we are entering into tensive test stage and code updating is on-going. Please see our github code commits.

**Comment by luke1allison** [comment]
Will the $SEELE token be used in the ecosystem as planned in the original white paper?

**Comment by georgy4932** [comment]
This project lack complete respect for its community and investors. No matter how much code you have on GitHub it is still unacceptable and unprofessional to ignore your commmunity. These people have life’s and they are suffering the consequences of your incompetence!
