### ISSUE TITLE
这个项目是不是已经死了啊？

### ISSUE THREAD

**Issue by Aoseala** [seeleteam/go-seele#923]
目前就两个人在提交代码，而且都是在改写皮毛的东西，根本改不动核心！ 你们的CTO刘文思已经自己创业开公司了，官网还挂着人家的头像。 seele 元一 真是令人恶心的项目，令人恶心的团队！

**Comment by whytecleon** [comment]
刘文思从未担任首席技术官。自从他离开后，团队应该从网站上删除他的详细信息。更新缓慢的方式令人厌恶。

**Comment by Aoseala** [comment]
不仅更新缓慢，而且现在就两个人在更新代码，更新的都是一些皮毛的东西，这两个开发人员估计是新手，根本改不动，这才是最要命的！

**Comment by Aoseala** [comment]
什么毕伟、郑茂林估计也跑路了，不知道是谁还在继续欺骗用户

**Comment by whytecleon** [comment]
放松，他们正在工作，肯定会提供。
